name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./LearnCollectInst.Api/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/learncollectinst.api:$(date +%s)
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/learncollectinst.api
